[package]
name = "omni"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["tokio"] }
reqwest = "0.13.2"
async-trait = "0.1.83"
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread", "time", "net"] }
axum = "0.7"
